### ISSUE TITLE
windows opencv-python .DLL import package

### ISSUE THREAD

**Issue by Ehsan2754** [Ahuratus/Trajectory-Detection-Web-services#1]
In windows platforms, after installation of openCV on python in some cases, we have the error as following
``` 
>>> import cv2
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Program Files (x86)\JetBrains\PyCharm Community Edition 4.5.4\helpers\pydev\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
ImportError: DLL load failed: The specified module could not be found.
```

**Comment by Ehsan2754** [comment]
the issue is related to media pack requirement of ```opencv```. 
In 2020  builds of windows 10 or later, as well as windows 11 the media pack is deleted. you may install the media pack on your machine by running the following command on your **powershell**:
```
 Get-WindowsCapability -online | Where-Object -Property name -like "*media*" | Add-WindowsCapability -Online
```
